### ISSUE TITLE
Need a Webpage ("Booking.html")

### ISSUE THREAD

**Issue by shakkeelaraoof** [shakkeelaraoof/Car_rental-Web#1]
We need a Webpage for Booking Portal. To book the Service for cars.
any interested persons can make

**Comment by G0V1NDK** [comment]
Do you need only an HTML file?

**Comment by shakkeelaraoof** [comment]
Got the Page

**Comment by shakkeelaraoof** [comment]
Our one Teammate has already Committed this and the Closed @AFEEF12345
