### ISSUE TITLE
Create a Webpage ("Service.html")

### ISSUE THREAD

**Issue by shakkeelaraoof** [shakkeelaraoof/Car_rental-Web#2]
Our Website need a webpage for showing the service list of the Company

**Comment by trishitchar** [comment]
Hey, Can you please assign me this task.

**Comment by NayanDeshmukh2001** [comment]
already working on it please assign it to me

**Comment by JassuSidhu6969** [comment]
I have created the services page for your website already! you can assign me to this task so I will upload services.html

**Comment by shakkeelaraoof** [comment]
The Task is Completed by @AFEEFALISHAN
